# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Google Workspace MCP
version: "0.1.9"
slug: google_workspace_mcp
description: Google Workspace MCP app for Home Assistant
url: "https://github.com/zxdavb/my-ha-apps/tree/main/google_workspace_mcp"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
map:
  - share:rw
ports:
  8000/tcp: 8000
options:
  google_oauth_client_id: ""
  google_oauth_client_secret: ""
  oauthlib_insecure_transport: false
  google_client_secret_path: ""
  user_google_email: ""
  workspace_mcp_credentials_dir: "/data/google_workspace_credentials"
  workspace_external_url: "https://hass.example.com"
  server:
    workspace_mcp_base_uri: "http://localhost"
    workspace_mcp_host: "0.0.0.0"
    workspace_mcp_port: 8000
    workspace_mcp_transport: "streamable-http"
  tool_selection:
    workspace_mcp_tools: ""
    workspace_mcp_tool_tier: "core"
    workspace_mcp_read_only: false
    workspace_mcp_permissions: ""
  oauth21:
    mcp_enable_oauth21: true
    workspace_mcp_stateless_mode: false
    external_oauth21_provider: false
    workspace_mcp_oauth_proxy_storage_backend: "disk"
    fastmcp_server_auth_google_jwt_signing_key: ""
    google_oauth_redirect_uri: ""
    oauth_custom_redirect_uris: ""
    oauth_allowed_origins: ""
    workspace_mcp_allowed_client_redirect_uris: "https://claude.ai/api/mcp/auth_callback,https://claude.com/api/mcp/auth_callback"
  local_files:
    allowed_file_dirs: "/share"
  access:
    single_user: false
schema:
  google_oauth_client_id: "str"
  google_oauth_client_secret: "password?"
  oauthlib_insecure_transport: "bool"
  google_client_secret_path: "str?"
  user_google_email: "str?"
  workspace_mcp_credentials_dir: "str?"
  workspace_external_url: "str?"
  server:
    workspace_mcp_base_uri: "str?"
    workspace_mcp_host: "str"
    workspace_mcp_port: "int"
    workspace_mcp_transport: "list(stdio|streamable-http)"
  tool_selection:
    workspace_mcp_tools: "str?"
    workspace_mcp_tool_tier: "list(core|extended|complete)"
    workspace_mcp_read_only: "bool"
    workspace_mcp_permissions: "str?"
  oauth21:
    mcp_enable_oauth21: "bool"
    workspace_mcp_stateless_mode: "bool"
    external_oauth21_provider: "bool"
    workspace_mcp_oauth_proxy_storage_backend: "list(memory|disk|valkey)"
    fastmcp_server_auth_google_jwt_signing_key: "password?"
    google_oauth_redirect_uri: "str?"
    oauth_custom_redirect_uris: "str?"
    oauth_allowed_origins: "str?"
    workspace_mcp_allowed_client_redirect_uris: "str?"
  local_files:
    allowed_file_dirs: "str?"
  access:
    single_user: "bool"
